vfa: bank client

bank:
	gcc -c bank.c -ansi -Wall -pedantic-errors -std=gnu99
	gcc -o Banka bank.o -lrt

client:
	gcc -c client.c -ansi -Wall -pedantic-errors -std=gnu99
	gcc -o Client client.o -lrt



clean:
	rm -f *.o Banka Client
	clear

